// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 開発用のシード。npx prisma db seed で実行する。
    // TypeScript のまま走らせるため tsx を使う（パスエイリアスも解決される）
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // 既定値は lib/prisma.ts と揃えること。ずれると CLI とアプリが別のDBを見てしまう。
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
